<참조: https://www.tensorflow.org/tutorials/customization/custom_layers?hl=ko>

## 사용자 정의 층

In [1]:
import tensorflow as tf

### 01. Layer
  - 머신러닝 모델 : 비교적 단순한 층(layer)을 조합하고 쌓아서 표현가능합니다
  - 텐서플로는 여러 표준형 층을 제공
    - 사용자들은 고유의 특화된 층을 작성하거나
    - 기존 층의 조합으로 쉽게 만들 수 있습니다

- tf.keras.layers package에서 층(layer)은 객체
  - 층을 구성하려면 간단히 객체를 생성합니다
  - layer의 첫 번째 인수로 출력 차원 또는 채널을 선정합니다  
    
- 입력 차원의 수는 층을 처음 실행할 때 유추할 수 있습니다
  - 복잡한 모델에서는 입력 차원의 수를 제공하는 것이 유용할 수 있습니다.

In [2]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

- tensorflow에서 미리 구성되어 있는 층
  - Dense : fully-connected
  - Conv2D
  - LSTM
  - BatchNormalization
  - Dropout  
    
  - 참조 문서 : https://www.tensorflow.org/api_docs/python/tf/keras/layers?hl=ko

In [3]:
tf.zeros([10, 5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### 이 부분의 결과를 잘 알지 못합니다

In [5]:
layer(tf.zeros([3, 5]))

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
layer(tf.zeros([3, 4]))  # input_shape와 형태가 달라서 오류

ValueError: Input 0 of layer dense_1 is incompatible with the layer: expected axis -1 of input shape to have value 5 but received input with shape (3, 4)

- layer
  - layer.variables : 층 안의 모든 변수를 확인할 수 있습니다.
  - layer.trainable_variables : 훈련 가능한 변수를 확인할 수 있습니다
  - fully-connected layer : weight / biases를 위한 변수를 가집니다

In [9]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.63174725,  0.2245413 , -0.40712088,  0.29714632, -0.48335415,
          0.36322963,  0.3486405 ,  0.3058815 , -0.17080233,  0.3407877 ],
        [-0.5446694 , -0.00430244,  0.5965473 ,  0.5768562 ,  0.02734649,
         -0.02158999,  0.22843397, -0.29991525, -0.5031674 , -0.45338422],
        [-0.26000994, -0.3455395 , -0.6077629 , -0.00519168,  0.39173728,
         -0.23544157,  0.535695  ,  0.08076084, -0.03909618, -0.46358162],
        [ 0.2829317 ,  0.44092268,  0.58469814,  0.02507758,  0.2564667 ,
         -0.24720374, -0.4041831 ,  0.21552008, -0.55923545, -0.20571214],
        [ 0.6011686 ,  0.00690281,  0.567872  ,  0.2121498 ,  0.07092607,
         -0.05902416, -0.24375805,  0.14211392,  0.42058522,  0.27720457]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [10]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.63174725,  0.2245413 , -0.40712088,  0.29714632, -0.48335415,
          0.36322963,  0.3486405 ,  0.3058815 , -0.17080233,  0.3407877 ],
        [-0.5446694 , -0.00430244,  0.5965473 ,  0.5768562 ,  0.02734649,
         -0.02158999,  0.22843397, -0.29991525, -0.5031674 , -0.45338422],
        [-0.26000994, -0.3455395 , -0.6077629 , -0.00519168,  0.39173728,
         -0.23544157,  0.535695  ,  0.08076084, -0.03909618, -0.46358162],
        [ 0.2829317 ,  0.44092268,  0.58469814,  0.02507758,  0.2564667 ,
         -0.24720374, -0.4041831 ,  0.21552008, -0.55923545, -0.20571214],
        [ 0.6011686 ,  0.00690281,  0.567872  ,  0.2121498 ,  0.07092607,
         -0.05902416, -0.24375805,  0.14211392,  0.42058522,  0.27720457]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

#### 이 부분도 결과를 잘 모르겠습니다. 
- 하지만 일단 넘어가고 튜토리얼 학습이 끝난 후에도 모르면 그때 다시 짚어볼 예정입니다.
- 그래서 이렇게 표시해둡니다.

### 02. 사용자 정의 층 구현
-  __init__ : 층에 필요한 매개변수를 입력받습니다
- build, 입력 텐서의 크기를 얻고 남은 초기화를 진행할 수 있습니다
- call, forward computation을 진행할 수 있습니다

In [11]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    def build(self, input_shape):
        self.kernel = self.add_variable('kernel',
                                       shape=[int(input_shape[-1]),
                                             self.num_outputs])
        
    def cal(self, input):
        return tf.matmul(input, self.kernel)

In [12]:
layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(10, 5), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.5329868 , -0.545226  , -0.29809928, -0.3191119 ,  0.51729935,
         0.17711318, -0.37608805,  0.10321456,  0.49123412,  0.57430667],
       [-0.35332444, -0.42599759,  0.50374025, -0.62148005,  0.536534  ,
         0.01142848, -0.5168505 ,  0.63214463, -0.5039146 ,  0.49229282],
       [-0.07961744, -0.00076598, -0.17630208, -0.49516004, -0.43849906,
        -0.21256053, -0.13767186,  0.12444073,  0.2635396 ,  0.30963677],
       [-0.14600581,  0.41410965, -0.49273264,  0.35357493, -0.43954688,
        -0.53076875, -0.507882  ,  0.10101515, -0.51822263,  0.6082937 ],
       [-0.58203423, -0.11935079,  0.61440164, -0.39394736,  0.5338568 ,
        -0.4486835 ,  0.56326085, -0.229

C:\Users\jjanh_000\anaconda3\lib\site-packages\keras\engine\base_layer.py:2223: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


### 03. 모델 : 층 구성

In [13]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        x += input_tensor
        return tf.nn.relu(x)

In [14]:
block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0']


#### 위에 작성한 코드를 tf.keras.Sequential을 사용하여 간단하게 구현한 것입니다.

In [15]:
my_seq = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1, 1), input_shape=(None, None, 3)),
    tf.keras.layers.BatchNormalization(),
    
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    
    tf.keras.layers.Conv2D(3, (1, 1)),
    tf.keras.layers.BatchNormalization()
])

In [16]:
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>